# JARファイルパス（scriptフォルダからの相対パス）
JAR_PATH=../lib/setfixedassetaccountcode-0.0.1-SNAPSHOT.jar
# 外部設定ファイルパス（application.yaml）（scriptフォルダからの相対パス）
CONFIG_PATH=../conf/application.yaml
JAVA_PATH=C:/Users/User49/AppData/Local/Programs/Eclipse Adoptium/jdk-17.0.20.8-hotspot/bin/java.exe
# リトライ回数
RETRY_COUNT=3
# リトライ時のスリープ時間（秒）
SLEEP_SECONDS=5
