spring:
  application:
    name: setfixedassetaccountcode
  datasource:
    url: jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=kanjou_ph3;encrypt=true;trustServerCertificate=true
    username: sa
    password: password
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
logging:
  level:
    com.zaxxer.hikari: warn
  file:
    name: C:\AIRead_ETL\logs\setfixedassetaccountcode.log
    appender.console.encoding: UTF-8
csv:
  outPath: C:\AIRead_Report\CSV\
